### ISSUE TITLE
create navbar

### ISSUE THREAD

**Issue by harshitjain156** [harshitjain156/my_portfollio_hacktoberfest#5]

**Comment by Eyesnatcher-coder** [comment]
hey @harshitjain156 please assign this issue to me, also please tell how you wanted navbar to look like a picture or something.

**Comment by Shaliniyadav8130** [comment]
Hey @harshitjain156  please assign me this issue.

**Comment by harshitjain156** [comment]
ok
you will add according youself.

**Comment by Abhishekvermaa** [comment]
if someone is not working then assign me this issue

**Comment by Eyesnatcher-coder** [comment]
Hey @harshitjain156 , I have created the navbar please  review and merge.

**Comment by harshitjain156** [comment]
done
